spring.application.name=kursovaya

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

upload.path=${UPLOAD_PATH:uploads}
spring.mvc.static-path-pattern=/uploads/**

token.signing.key=${JWT_SECRET}
